language: python
python:
- 2.7
install:
- pip install --upgrade setuptools
- pip install coveralls
- pip install cython
script:
- python setup.py test
after_success:
- coverage run --source=beeswarm setup.py -q nosetests
- coveralls
deploy:
  provider: pypi
  user: Johnny.Vestergaard
  password:
    secure: "Ibsqv94uYPdzjm4lz0czXEpxQLhpkLIgkIT9awfROWOChd6EXvOgfwLtgzq4KRvQHcR6mVdgIzWoVRaw6b0+iBUomCyzo7ZrbhB37NlH5Kv4ZaNOkF5cwVFbHLwqOY6C8D4WD7+lDolPj3RYShlbIasZ0rLmO6ReWdYnKcV9VMQ="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: honeynet/beeswarm
    condition: $TRAVIS_TAG =~ ^Release_[0-9]+[.][0-9]+[.][0-9]+
