language: python
python:
  - 2.7
install:
  - pip install --upgrade setuptools
  - pip install coveralls
  - pip install cython
script:
  - python setup.py test
after_success:
  - coverage run --source=beeswarm setup.py -q nosetests
  - coveralls
