language: python

python:
  - "2.7"
before_install:
 - sudo apt-get update
 - sudo apt-get install python-dev libevent-dev
 - sudo apt-get install swig
# command to install dependencies
install:
  - pip install -e git+https://github.com/rep/hpfeeds.git#egg=hpfeeds
  - pip install -r requirements.txt
# command to run tests
script:
 - nosetests
 
after_success:
 - pip install --upgrade distribute
 - pip install --upgrade coveralls coverage sh
 - coverage run --source=beeswarm setup.py -q nosetests
 - coveralls
