language: python

python:
  - "2.7"

# command to run tests
script:
 - python setup.py test

after_success:
 - pip install --upgrade distribute
 - pip install --upgrade coveralls coverage sh
 - coverage run --source=beeswarm setup.py -q nosetests
 - coveralls
