language: python
python:
  - 2.7
install:
  - pip install --upgrade setuptools
  - pip install -e .
  - pip install coveralls
script:
  - coverage run --source=faker setup.py test
after_success:
  - coveralls
