language: python
services: mongodb
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - "sudo apt-get update"
 - "sudo apt-get install python-nose"
 - "sudo apt-get install python-dev libevent-dev"
# command to install dependencies
install:
  - "sudo pip install -e git+https://github.com/rep/hpfeeds.git#egg=hpfeeds"
  - "sudo pip install -r requirements.txt --use-mirrors"
  - "sudo pip install coveralls --use-mirrors"
  - "sudo pip install python-coveralls --use-mirrors"
# command to run tests
script:
 - nosetests 
 
after_success:
 - coveralls
