language: python
python:
  - 2.7
install:
  - pip install --upgrade setuptools
  - pip install coveralls
  - pip install cython
script:
  - python setup.py test
after_success:
  - coverage run --source=beeswarm setup.py -q nosetests
  - coveralls
deploy:
  provider: pypi
  user: Johnny.Vestergaard
  password:
    secure: dMH8ewnka+UkTMGqmgeuT8AzWXJTtCPx7le0hPIJrGV4cnfSDlWwkU145aTMQgjia9BkW+KeR+nK9Q+ERmiJyencm0lUJ9pZj9i49OmLmppOv/U3kEvWFlLCe+HopXVk4VzFnlen7nNMVUNpQoy39WE1WulSxGtbAdXXUX/ZKSw=
  on:
    repo: honeynet/beeswarm
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^Release_[0-9]+[.][0-9]+[.][0-9]+"
