language: python
services: mongodb
python:
  - "2.7"
before_install:
 - "sudo apt-get update"
 - "sudo apt-get install python-nose"
# command to install dependencies
install:
  - "sudo pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
 - nosetests