language: python

python:
  - "2.7"
before_install:
 - sudo apt-get update
 - sudo apt-get install python-dev libevent-dev

# command to run tests
script:
 - python setup.py test

after_success:
 - pip install --upgrade distribute
 - pip install --upgrade coveralls coverage sh
 - coverage run --source=beeswarm setup.py -q nosetests
 - coveralls
